Repository CHZZK-Study/HOWMeet-Frontend, pull requests merged in 2024-10, with the labels that each got.

#66 [FEAT/HM-168]: 초대링크 일정 이름 추가
  src/apis/meeting.ts
  src/components/login/TeammateLogin.tsx
  src/hooks/useMeetingInfo.ts
Labels: ✨feature

#65 [Style/HM-166] 배포 디자인 수정
  index.html
  src/components/home/UpComming.tsx
  src/components/newmeeting/ShareMeeting.tsx
  src/components/roomdetail/Attenders.tsx
  src/components/roomdetail/CreateNewMeeting.tsx
  src/pages/HomePage.tsx
  src/pages/RoomPage.tsx
  src/styles/theme.ts
Labels: 🎨 style

#67 [DESIGN]/HM-145 히트맵 디자인 수정 및 스켈레톤 UI생성
  src/components/meeting/result/UrlShareModal.tsx
  src/components/meeting/select/TimeSelectCompModal.tsx
  src/components/meeting/timetable/BaseTimeTable.tsx
  src/components/meeting/timetable/SelectTimeCell.tsx
  src/mocks/data/timeTableData.ts
  src/pages/DecisionPage.tsx
  src/pages/ResultPage.tsx
  src/pages/SelectPage.tsx
Labels: 🎨 style, 👩🏻‍💻frontend, 🪄refactor

#69 [FIX/HM-170]: 비회원 로그인 리다이렉트 오류 수정
  src/components/login/TeammateLogin.tsx
Labels: 🐛fix

#71 [FIX/HM-170]: callback 오류 수정
  src/constants/storage.ts
  src/hooks/useSocialLogin.ts
Labels: 🐛fix

#75 [Fix/HM-169] 일정 배포 이슈 해결 및 방 링크 공유 이슈 테스팅
  src/App.tsx
  src/components/roomdetail/ConfirmList.tsx
  src/hooks/useMakeMemberMeeting.ts
  src/hooks/useResetStore.ts
  src/pages/RoomPage.tsx
  src/routes/index.tsx
  src/store/meeting/useTimeStore.ts
  src/store/useDateStore.ts
  src/store/useMeetingStore.ts
  src/store/useTimeStore.ts
Labels: 🐛fix

#76 [Release] 배포 테스팅 이슈 해결
  src/App.tsx
  src/components/roomdetail/ConfirmList.tsx
  src/hooks/useMakeMemberMeeting.ts
  src/hooks/useResetStore.ts
  src/pages/RoomPage.tsx
  src/routes/index.tsx
  src/store/meeting/useTimeStore.ts
  src/store/useDateStore.ts
  src/store/useMeetingStore.ts
  src/store/useTimeStore.ts
Labels: 🐛fix

#77 [FIX/HM-170]: 멤버 추가 get -> patch 변경
  src/apis/user.api.ts
Labels: 🐛fix

#79 [FIX/HM-170]: 멤버 추가, 리다이렉트 오류 수정
  src/components/login/TeammateLogin.tsx
  src/constants/storage.ts
  src/hooks/useMeetingInfo.ts
  src/hooks/useRedirect.ts
  src/hooks/useRoom.tsx
  src/hooks/useSocialLogin.ts
  src/pages/LoginPage.tsx
  src/pages/RoomPage.tsx
  src/pages/SelectPage.tsx
Labels: 🐛fix

#81 [FIX/HM-170]: 멤버 추가 api 요청 수정
  src/apis/user.api.ts
  src/hooks/useSocialLogin.ts
Labels: 🐛fix

#83 [Fix/HM-169] 방 공유 테스트
  src/pages/RoomPage.tsx
Labels: 🐛fix

#84 [Test] 방 공유 기능 테스트를 위한 배포
  src/pages/RoomPage.tsx
Labels: 🐛fix

#85 [Fix/HM-169] 배포 이슈 수정
  src/pages/NewMeetingPage.tsx
  src/pages/RoomPage.tsx
Labels: 🐛fix

#87 [Fix/HM-169]: 방 공유 테스팅
  src/hooks/useSocialLogin.ts
Labels: 🐛fix

#91 [Fix/HM-169]: 확정 일정 시간 수정
  src/apis/room.api.ts
  src/components/roomdetail/ConfirmList.tsx
  src/types/room.d.ts
Labels: 🐛fix

#93 [Fix/HM-169] 확정일정 날짜 수정
  src/components/roomdetail/ConfirmList.tsx
  src/types/room.d.ts
Labels: 🐛fix
