Repository CHZZK-Study/HOWMeet-Frontend, pull requests merged in 2024-09, with the labels that each got.

#26 [FEAT/HM-142]: 비회원 로그인 플로우 변경
  src/apis/user.api.ts
  src/components/bottomsheet/LogOut.tsx
  src/components/bottomsheet/TimePicker.tsx
  src/components/common/Button.tsx
  src/components/login/DefaultLogin.tsx
  src/components/login/LoginForm.tsx
  src/components/login/LoginGuide.tsx
  src/components/login/MemberLogin.tsx
  src/components/login/NonMemberLogin.tsx
  src/components/login/SocialLoginButtons.tsx
  src/components/login/TeammateLogin.tsx
  src/components/meeting/result/ResultTimeSelectModal.tsx
  src/components/meeting/select/TimeSelectCompModal.tsx
  src/hooks/useLogin.ts
  src/hooks/useSocialLogin.ts
  src/models/user.model.ts
  src/pages/DecisionPage.tsx
  src/pages/LoginPage.tsx
  src/pages/MainPage.tsx
  src/pages/NewMeetingPage.tsx
  src/pages/SelectPage.tsx
  src/store/userStore.ts
  src/styles/components/container.ts
Labels: ✨feature

#27 [API/HM-155]: 알림 API 연동
  src/apis/notification.api.ts
  src/lib/notification.ts
  src/types/notification.ts
Labels: 🔧 API

#32 [FEAT/HM-145] 서버 api 수정 및 디자인 변경
  .env
  package-lock.json
  package.json
  public/assets/font/font.css
  public/assets/icons/common/share.svg
  public/service-worker.js
  src/App.tsx
  src/apis/API.md
  src/apis/instance.ts
  src/components/common/Header.tsx
  src/components/common/ToolTip.tsx
  src/components/meeting/result/AttendStatusHeader.tsx
  src/components/meeting/result/ResultBottomSheet.tsx
  src/components/meeting/result/ResultInfoComp.tsx
  src/components/meeting/result/ResultNavbar.tsx
  src/components/meeting/result/ResultTimeTable.tsx
  src/components/meeting/result/UrlShareModal.tsx
  src/components/meeting/result/nextWorkingFIle/SelectNavbar.tsx
  src/components/meeting/select/HeaderToolTip.tsx
  src/components/meeting/select/SelectableTimeTable.tsx
  src/components/meeting/select/TimeSelectTitle.tsx
  src/components/meeting/timetable/BaseTimeTable.tsx
  src/components/meeting/timetable/ResultTimeCell.tsx
  src/components/meeting/timetable/SelectTimeCell.tsx
  src/constants/api.ts
  src/hooks/useCopyUrl.ts
  src/hooks/useTimeTableData.ts
  src/hooks/useToolTip.ts
  src/lib/pwaConfig.ts
  src/main.tsx
  src/mocks/data/selectedTimeData.ts
  src/mocks/data/timeTableData.ts
  src/mocks/handlers.ts
  src/pages/DecisionPage.tsx
  src/pages/ResultPage.tsx
  src/pages/SelectPage.tsx
  src/routes/index.tsx
  src/styles/ToasterStyles.ts
  src/styles/components/container.ts
  src/types/timeTableTypes.d.ts
  src/utils/meeting/timetable/formatDateTime.ts
Labels: ✨feature, 🎨 style, 👩🏻‍💻frontend, 🪄refactor

#31 [Style/HM-54] ci,cd 오타 수정
  .github/workflows/main.yml
  src/pages/NewMeetingNonMemberPage.tsx
Labels: ⚙️chore

#30 [FEAT/HM-155]: 초대링크 로그인 구현
  src/App.tsx
  src/apis/instance.ts
  src/apis/user.api.ts
  src/components/bottomsheet/LogOut.tsx
  src/components/login/LoginForm.tsx
  src/components/login/SocialLoginButtons.tsx
  src/components/login/TeammateLogin.tsx
  src/hooks/useLogin.ts
  src/hooks/useLogout.ts
  src/hooks/useSocialLogin.ts
  src/models/user.model.ts
  src/pages/LoginPage.tsx
  src/pages/NewMeetingNonMemberPage.tsx
  src/pages/SelectPage.tsx
  src/store/meeting/useStepStore.ts
  src/store/userStore.ts
  src/types/auth.d.ts
  src/utils/auth.ts
  src/utils/token.ts
Labels: ✨feature

#33 [FIX/HM-155]: 토큰 post 오류 수정
  src/apis/instance.ts
  src/apis/notification.api.ts
  src/pages/SelectPage.tsx
Labels: 🐛fix

#34 [API/HM-155]: 멤버 추가 api 연동
  src/apis/user.api.ts
  src/hooks/useSocialLogin.ts
  src/pages/SelectPage.tsx
Labels: 🔧 API

#36 [Feat/HM-112] 회원 방만들기 및 일정 만들기 api 연동
  public/assets/icons/index.ts
  src/apis/meeting.ts
  src/apis/room.api.ts
  src/components/newmeeting/ConfirmMeeting.tsx
  src/components/room/ConfirmContent.tsx
  src/components/roomlist/CreateRoomButton.tsx
  src/constants/path.ts
  src/hooks/useConvertTime.ts
  src/hooks/useMakeMemberMeeting.ts
  src/hooks/useMakeRoom.ts
  src/models/meeting.model.ts
  src/models/room.model.ts
  src/pages/ConfirmMeeting.tsx
  src/pages/MakingRoomPage.tsx
  src/pages/NewMeetingPage.tsx
  src/store/makeroom/useMakeRoomStore.ts
  src/styles/components/meeting/select.ts
Labels: 🔧 API

#35 [Feat/HM-145] 서버 api 연동 작업
  src/App.tsx
  src/components/meeting/result/AttendStatusHeader.tsx
  src/components/meeting/result/ResultBottomSheet.tsx
  src/components/meeting/result/ResultInfoComp.tsx
  src/components/meeting/result/ResultTimeSelectModal.tsx
  src/components/meeting/select/SelectableTimeTable.tsx
  src/components/meeting/timetable/BaseTimeTable.tsx
  src/components/meeting/timetable/ResultTimeCell.tsx
  src/constants/api.ts
  src/hooks/useTimeTableData.ts
  src/pages/DecisionPage.tsx
  src/pages/ResultPage.tsx
  src/pages/SelectPage.tsx
  src/styles/components/container.ts
  src/utils/meeting/timetable/formatDateTime.ts
Labels: 🐛fix

#37 [Feat/HM-126] 비회원 일정만들기 api 구현 및 연동
  src/apis/meeting.api.ts
  src/components/login/DefaultLogin.tsx
  src/components/newmeeting/ConfirmMeeting.tsx
  src/constants/api.ts
  src/constants/path.ts
  src/hooks/useConvertTime.ts
  src/hooks/useNonMemberMeeting.ts
  src/models/meeting.model.ts
Labels: 🔧 API

#38 [Feat/HM-126] 비회원 일정 기능 구현
  src/components/login/LoginForm.tsx
  src/components/newmeeting/LoginNonMember.tsx
  src/hooks/useNonMemberMeeting.ts
  src/store/meeting/useNonMemberMeeting.ts
Labels: 🔧 API

#39 [FIX/HM]: 로그인 오류 수정, 링크 복사 기능 추가
  .env
  src/components/newmeeting/ShareMeeting.tsx
  src/store/meeting/useNonMemberMeeting.ts
Labels: 🐛fix

#40 [Feat/HM-144] 방 목록 조회 및 방 상세 조회 api 연동
  package-lock.json
  package.json
  src/apis/room.api.ts
  src/components/bottomsheet/LogOut.tsx
  src/components/common/Header.tsx
  src/components/home/HomeHeader.tsx
  src/components/home/UpComming.tsx
  src/components/roomdetail/Attenders.tsx
  src/components/roomdetail/ConfirmList.tsx
  src/components/roomdetail/CreateNewMeeting.tsx
  src/components/roomdetail/NonConfirmList.tsx
  src/components/roomlist/CreateRoomButton.tsx
  src/components/roomlist/RoomItem.tsx
  src/components/roomlist/RoomList.tsx
  src/constants/api.ts
  src/constants/path.ts
  src/hooks/useClosestMeeting.ts
  src/hooks/useMakeMemberMeeting.ts
  src/hooks/useRoom.tsx
  src/hooks/useRoomList.ts
  src/models/room.model.ts
  src/pages/ConfirmMeeting.tsx
  src/pages/HomePage.tsx
  src/pages/MeetingListPage.tsx
  src/pages/NewMeetingPage.tsx
  src/pages/RoomListPage.tsx
  src/pages/RoomPage.tsx
  src/routes/index.tsx
  src/styles/components/emptybox.ts
  src/styles/theme.ts
  src/types/room.d.ts
Labels: 🔧 API

#43 [Fix/HM-161]: ci,cd문서 수정
  .env
  .github/workflows/main.yml
  src/constants/api.ts
Labels: 📃docs

#44 [FEAT/HM-145] ignore 설정
  .gitignore
  src/components/meeting/result/AttendStatusHeader.tsx
  src/components/meeting/timetable/ResultTimeCell.tsx
Labels: ⚙️chore

#47 [Fix/HM-164]: 방 목록 페이지 전체 참여 카운트적용
  .env
  src/models/room.model.ts
  src/pages/RoomListPage.tsx
Labels: 🐛fix

#55 [FIX]: redirect 오류 수정
  src/pages/SelectPage.tsx
Labels: 🐛fix

#63 [Fix/HM-165]: 배포 이슈 해결 테스팅
  src/apis/room.api.ts
  src/hooks/useMakeMemberMeeting.ts
  src/hooks/useRoomList.ts
  src/pages/RoomPage.tsx
Labels: 🐛fix

#64 [Fix] 배포이슈 테스팅 수정
  src/apis/room.api.ts
  src/hooks/useMakeMemberMeeting.ts
  src/hooks/useRoomList.ts
  src/pages/RoomPage.tsx
Labels: 🐛fix
